# Generated by Django 5.2.9 on 2025-12-15 17:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=255)),
                ('identifier_type', models.CharField(max_length=10)),
                ('attempt_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['identifier', 'identifier_type', 'attempt_time'], name='accounts_lo_identif_a1566c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthenticationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_attempted', models.EmailField(db_index=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('ACCOUNT_LOCKED', 'Account Locked'), ('LOGOUT', 'Logout')], db_index=True, max_length=20)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'authentication event',
                'verbose_name_plural': 'authentication events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['email_attempted', 'event_type', 'timestamp'], name='accounts_au_email_a_098f0e_idx'), models.Index(fields=['ip_address', 'event_type', 'timestamp'], name='accounts_au_ip_addr_76d87f_idx')],
            },
        ),
    ]
