# Generated by Django 5.2.9 on 2025-12-15 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginattempt_authenticationevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('ACCOUNT_LOCKED', 'Account Locked'), ('LOGOUT', 'Logout'), ('TOKEN_REUSE', 'Token Reuse Detected')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('jti', models.CharField(db_index=True, max_length=36, unique=True)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='accounts.refreshtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'refresh token',
                'verbose_name_plural': 'refresh tokens',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='accounts_re_user_id_aeede0_idx')],
            },
        ),
    ]
